version: '3'
services:
  aquos-remote:
    container_name: AquosRemote
    build: .
    ports:
      - "7000:7000"
    volumes:
      - ./:/app
    command: >
      bash -c " deno task build &&
      deno run -A main.ts"